### ISSUE TITLE
Release publishing is broken

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#294]
See https://github.com/rsocket/rsocket-java/blob/1.0.x/gradle/buildViaTravis.sh#L7

Due to permission issues after #268

**Comment by yschimke** [comment]
Working now Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/rsocket/rsocket-core/0.9-SNAPSHOT/rsocket-core-0.9-SNAPSHOT.pom

**Comment by yschimke** [comment]
https://travis-ci.org/rsocket/rsocket-java/builds/243318904

:rsocket-core:bintrayUpload FAILED
:rsocket-examples:publishNebulaPublicationToMavenLocal
:rsocket-examples:bintrayUpload

**Comment by yschimke** [comment]
Status: working for snapshots but failing for tagged releases

**Comment by benjchristensen** [comment]
I've turned on info logging to show more of what's going on, but I still don't understand what is preventing bintray uploads.

https://travis-ci.org/rsocket/rsocket-java/builds/243399276#L2835

I was able to manually upload a file via curl with the credentials, so bintray accepts files.

**Comment by benjchristensen** [comment]
Here is where snapshots are going: https://oss.jfrog.org/artifactory/oss-snapshot-local/io/rsocket/rsocket-core/0.9-SNAPSHOT/

**Comment by yschimke** [comment]
Is it possible that the build plugins are filtering for reactivesocket instead of rsocket?

```
Executing task ':rsocket-core:publishNebulaPublicationToMavenLocal' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
```

**Comment by benjchristensen** [comment]
Maybe but I couldn't tell where that would occur when reading through the Groovy code. As while looking it seems everything ultimately gets defined through configuration and the build.gradle file has everything set to rsocket. 

If this is the issue, it's only the prefix that would matter. I suppose we could do a test where we rename a module to reactivesocket-something. 

But, I think the only reason we would want a 'RSocket' Nebula plugin versus 'ReactiveSocket' one is so we don't depend on an external project that could change or go away (as ReactiveSocket  will). That's why the plugin was originally cloned from RxJava to ReactiveSocket, just to not have weird transitive dependencies.

**Comment by yschimke** [comment]
Damn, well I'm out of ideas.  I don't want to rebuild this from scratch using the bintray plugin directly, as we essentially own the maintenance then.

@stevegury is there any newer version of these plugins we could use as a starting point and upgrade gradle if needed etc?

**Comment by yschimke** [comment]
Not sure exactly what fixes this in gradle 4, but it's in these magic lines

```
+            publications('mavenJava')
+
+            defaults {
+                // Reference to Gradle publications defined in the build script.
+                // This is how we tell the Artifactory Plugin which artifacts should be
+                // published to Artifactory.
+                publications('mavenJava')
+                publishArtifacts = true
+            }
         }
     }

+    artifactoryPublish {
+        dependsOn jar
+    }
```
