### ISSUE TITLE
Resume support

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#339]

**Comment by yschimke** [comment]
https://github.com/rsocket/rsocket-java/pull/340
https://github.com/rsocket/rsocket-java/pull/341

**Comment by yschimke** [comment]
Feel free to work steal this off me

**Comment by smaldini** [comment]
Reviving that issue since i came across the existing support in rsocket-js : https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-core/src/RSocketResumableTransport.js - In general I wonder if it implies some adjustments in the existing contract for DuplexConnection. In JS the connection exposes close/connect directly allowing for decoration and retry. In Java there is more separation of concerns here.

**Comment by robertroeser** [comment]
#558
