### ISSUE TITLE
Support binding Reactor Context to Metadata

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#373]
https://projectreactor.io/docs/core/snapshot/api/reactor/util/context/Context.html

Some apps may want to control metadata explicitly, but setting and retrieving Context in calls should be supported.

- Define a sensible JSON? CBOR? serialization for Metadata
- Make sure we propagate this internally e.g. we don't undo this by some choice of operators etc

**Comment by yschimke** [comment]
https://github.com/rsocket/rsocket-java/pull/379

**Comment by yschimke** [comment]
@nebhale do you have an opinion here? Should we build in support at some level for Reactor Context?  I'm tempted to close but curious on your perspective.

My starting point was that using a Reactor based library should support Context by default, maybe with a simple switch to enable it on transport level.

**Comment by nebhale** [comment]
I was looking this issue over the other day and couldn’t quite understand what the usecase was.  Since both the metadata and data of each `Payload` frame is exposed to the user, wouldn’t they already have access to it on the receiver side, and then building `Payload`s on the sender side would allow them to be added directly.  Is there some scenario where the user wouldn’t have access to all the metadata and data of a frame?

**Comment by yschimke** [comment]
I think you’ve answered my question. Closing

**Comment by yschimke** [comment]
Regarding the use case, I'm used to Finagle where there is a Context preserved across multiple hops e.g. client -> http -> server -> thrift -> server2 -> ...

Things like Zipkin traceid are carried through automatically and allow tracking specific requests (traces) through multiple services without explicit support.  The argument against adding support in rsocket-java is probably that it isn't intended to be an opinionated framework like that and it's easier to build functionality on top of rsocket/reactor if its just supported/allowable.
