### ISSUE TITLE
ConnectionInterceptor per connection

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#432]
It would be helpful to have it, in addition to per client/server one. This change would allow external parties to develop missing parts of spec without contributing to this project, and depend on it instead.

**Comment by robertroeser** [comment]
Sounds good. Would you add this to the RSocketFactory, and have one for the request and one for the responder-  something like this?
```
RSocketFacotry
.receive()
.requestorConnectionInterceptor(Function<DuplexConnection,DuplexConnection> interceptor)
.responderConnectionInterceptor(Function<DuplexConnection,DuplexConnection> interceptor)
```

**Comment by yschimke** [comment]
Isn't this already possible via the connection plugins? n.b. This isn't heavily tested code, we use it for some stats collections, but it's possible it has bigger issues we still need to fix.

```
    RSocketFactory.connect().addConnectionPlugin(new DuplexConnectionInterceptor() {
      @Override public DuplexConnection apply(Type type,
          DuplexConnection duplexConnection) {
        if (type == Type.SOURCE) {
          return ...;
        }
        return duplexConnection;
      }
    });
```

**Comment by robertroeser** [comment]
I forgot that the connection pluging was per connection now too...yeah that will work. If it doesn't its just a matter of testing/fixing, and what not. I guess we can close the issue?

**Comment by mostroverkhov** [comment]
@yschimke With current DuplexConnectionInterceptor there is no way to share state between DuplexConnections of different types, as there is no guarantee those will relate to same connection (as far as we concerned). What we need is new DuplexConnectionInterceptor per connection `.addConnectionPlugin(() -> DuplexConnectionInterceptor)` 
@robertroeser not sure I follow your proposition. But for the sake of clarity, we wolud like to see `RSocketFactory.connect().addConnectionPlugin(Supplier<DuplexConnectionInterceptor>)` for Client (initiator of Connection) and `RSocketFacotry
.receive().addConnectionPlugin(Supplier<DuplexConnectionInterceptor>)` for Server (acceptor of Connection)

**Comment by yschimke** [comment]
@mostroverkhov OK, so for client it's fine as there is a single connection. But for a server you don't know which calls are related.  I think you can always make it work via the SOURCE, but I'm not surprised if we didn't get this easy and right first time.

```
RSocketFactory.connect().addConnectionPlugin(new DuplexConnectionInterceptor() {
      @Override public DuplexConnection apply(Type type,
          DuplexConnection duplexConnection) {
        if (type == Type.SOURCE) {
          return new MyPlugin(duplexConnection);
        }
        return duplexConnection;
      }
    });
```

This should create a single MyPlugin instance for each new connection, and it will see every Frame of the connection (stream 0, client mode, server mode).

The current API works well for stats as you can record counters differently for incoming "server" requests and outgoing "client" requests since a single connection is bi-directional.  But it may not be great for other use cases. 

Is there a concrete example of what you would like to do?  What sort of extensions?

**Comment by mostroverkhov** [comment]
example is my private wip on [leasing](https://github.com/mostroverkhov/reactivesocket-java/blob/lease-connection-interceptors/rsocket-core/src/main/java/io/rsocket/lease/LeaseInterceptor.java).
