### ISSUE TITLE
Frame reassembly application logic is insufficient

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#501]
`FrameReassembler` connection is applied only if `mtu>0`, but reassembly should always happen for incoming frames, and `mtu` must be used for outgoing frames

**Comment by nebhale** [comment]
What would be your expected behavior be if you attempted to apply the `FragmentationDuplexConnection` with a negative number?  At the moment it throws an exception preventing startup completely, but I get the sense that you'd like a different behavior?  Would you expect fragmentation to simply not happen but allow startup to proceed with reassembly?

More generally, what does the matrix of negative/zero/positive crossed with fragmentation/reassembly look like?

**Comment by mostroverkhov** [comment]
My concern is reassembly is happening conditionally - if one side of connection has `mtu = 0`,  it cant reassemble frames, coming from other side. Reassembly is not negotiated on setup, so any peer can send disassembled frames any time.

**Comment by mostroverkhov** [comment]
I suspect It is there from the beginning :). I am working on another rsocket implementation - so this is one of ton of issues I find comparing this implementation with spec.

**Comment by nebhale** [comment]
Understood.  Thank for the quick responses.  I'm working on a PR now.
