### ISSUE TITLE
Unexcepted outcome while using requestChannel

### ISSUE THREAD

**Issue by klopfdreh** [rsocket/rsocket-java#628]
Hell everyone,

first of all thanks a lot for the java implementation of RSocket. First some side notes:

RSocket version: 0.12.2-RC2
My example project: https://github.com/klopfdreh/rsocket_playground
Scenario: requestChannel

My output looks like this:

Server:
```java
d.k.r.playground.ServerController - Person added: {"name":"Jon","size":192,"age":11}
d.k.r.playground.ServerController - {"valid":true,"person":{"name":"Jon","size":192,"age":11}}
d.k.r.playground.ServerController - Person added: {"name":"Maria","size":170,"age":21}
```

Client:
```java
d.k.r.playground.ClientController - {"name":"Jon","size":192,"age":11}
d.k.r.playground.ClientController - {"name":"Maria","size":170,"age":21}
d.k.r.playground.ClientController - {"valid":true,"person":{"name":"Jon","size":192,"age":11}}
```
The first two lines of the client are information that are going to be sent to the server.
The last line is the response from server

The server receives both persons, but wraps only one into that PersonResponse object and sends it back to the client.

My expectation would be that the client receives another line with valid true for Maria.

To reproduce just checkout the project start ServerStarter as Java Application and afterwards start ClientStarter as Java Application.

Thanks for the help in advance.

**Comment by robertroeser** [comment]
@klopfdreh - Hi RC3 is out. There were some changes in RC2 that get shifted back to RC3. Can you try again?

**Comment by klopfdreh** [comment]
Hey @robertroeser - Sure! I am going to test it later this day. Thanks for your response. 👍

**Comment by klopfdreh** [comment]
Hi @robertroeser - I just tested the code with RC3 - same outcome. Maybe it is a fault of my code and I would be very pleased if you could just check it and maybe help me to find out the issue? I would be very pleased.

**Comment by robertroeser** [comment]
Hi @klopfdreh ,

@mostroverkhov will take a look

Thanks,
Robert

**Comment by mostroverkhov** [comment]
@klopfdreh I think [here](https://github.com/klopfdreh/rsocket_playground/blob/c7e5dd99759db13f70da50b630bd8d2c829a5a6f/src/main/java/de/klopfdreh/rsocket/playground/Server.java#L38) subscription has to be delayed until request `Publisher` is completed - then your implementation should produce expected results - something like
```
	@Override
	public Flux<Payload> requestChannel(Publisher<Payload> payloads) {
		Flux<Payload> request = Flux.from(payloads).publish().autoConnect(2);
		request.subscribe(serverController::processClientPayload);
	    return Flux.from(serverController).delaySubscription(request.then());
	}
```

**Comment by klopfdreh** [comment]
Thanks a lot for the help! I am a little bit confused about that, because I thought that when the subscription is applied the server is listening untit onComplete is called on client side. Can you explain why the delay is requiriert?

Thanks again for your time and help!

**Comment by OlegDokuka** [comment]
First of all - everything happens asynchronously and in your case concurrently (reactive streams have requestN behavior so there are no guarantees that this call will be done in the same thread as Publisher was generated.

The above statement leads to the fact that you are using inappropriate collection which is non-thread safe at all (you are lucky it worked at all);

Then, RSocket requestChannel sends the first payload along with type (kind of optimization) so you receive a requestChannel invocation and once you subscribe to the list the first element will be stored to the list. But, there are no guarantees the second element appears immediately. It could be produced a moment later, but you have a Publisher which does not take into account whether the stream from the client is completed and that Publisher produces that many onNext as many elements are in the queue at a moment of iterating. Since you have got only one for sure (happens before guarantees) you will observe one and completion.

That is why once you postpone subscription to your publisher until completion of the upstream, there will be a guarantee that all elements will be in the queue.

1) Pay attention to your ServerController which implements `Publisher`( which is incorrect implementation). If you are going to run your code against [Reactive-Streams TCK](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck) you will see that lots of tests will fail.
2) Remember, everything is async, and you must pay and additional care that you properly synchronize you pipeline (take a look at Processor paradigm. Reactor offers a few good implementations of it)
3) Use end to end chaining, for example, use `map` in order to convert payload and then convert the same stream back as an output

Regards,
Oleh

**Comment by klopfdreh** [comment]
Thanks a ton for this awesome explanation! Helps a lot!

**Comment by klopfdreh** [comment]
Hey @OlegDokuka - it has been a long time since I opened this issue. I did some refactoring and changed the implementation on server side to look like:

```java
    private class RSocketImpl extends AbstractRSocket {
        @Override
        public Flux<Payload> requestChannel(Publisher<Payload> payloads) {
            return Flux.from(payloads).doOnNext(payload -> {
                LOGGER.info("Received payload: [{}]", payload.getDataUtf8());
            }).map(payload -> serverController.processClientPayload(payload))
                    .subscribeOn(Schedulers.parallel());
        }
    }
```

In addition I removed the list and assumed that the handling of the payload is done within the processClientPayload method. (Like storage) This addresses point 1. / 3. For point 2. I have to take a deeper look into the Processor API. Any other hints on this - or is there something left opened on which I have to take a better look at?

Thanks a lot again for your help and good explanations!

Note: The output is also as expected, now. 😄

**Comment by OlegDokuka** [comment]
@klopfdreh Looks much better. I'm not sure I can say anything since I'm not seeing what is behind the `processClientPayload` method

**Comment by klopfdreh** [comment]
It only converts the request payload to a response payload - in this method I would do also something like database operations in a real case scenario.

https://github.com/klopfdreh/rsocket_playground/blob/master/src/main/java/de/klopfdreh/rsocket/playground/ServerController.java

**Comment by OlegDokuka** [comment]
@klopfdreh the only recommendation I can give possibly uses of ZERO_COPY mechanism which put a requirement on releasing `Payload`s manually, but increases performance significantly

**Comment by klopfdreh** [comment]
@OlegDokuka good point - I used ZERO_COPY, but forgot to release the payload!

Server:
```java
        @Override
        public Flux<Payload> requestChannel(Publisher<Payload> payloads) {
            return Flux.from(payloads).doOnNext(payload -> {
                LOGGER.info("Received payload: [{}]", payload.getDataUtf8());
            }).map(payload -> {
                try {
                    return serverController.processClientPayload(payload);
                } finally {
                    payload.release();
                }
            }).subscribeOn(Schedulers.parallel());
        }
```

Client:
```java
        this.socket.requestChannel(Flux.from(clientController)).doOnNext(payload -> {
            try {
                clientController.processServerPayload(payload);
            } finally {
                payload.release();
            }
        }).blockLast();
```

I applied a finally to both implementations.
