### ISSUE TITLE
There is no support for UDP in rsocket-netty-transport

### ISSUE THREAD

**Issue by shazin** [rsocket/rsocket-java#708]
Currently there is only support for TCP and Websocket for RSocket. It is very good to have UDP support as well because many applications use this protocol.

**Comment by linux-china** [comment]
@shazin   you can use RSocket with Aeron.  https://github.com/scalecube/rsocket-transport-aeron Some APIs change from RSocket and Aeron, and it can not be compiled.  I have a modified version https://github.com/linux-china/rsocket-transport-aeron   I think after RSocket 1.0, and Aeron support will be released soon.

**Comment by OlegDokuka** [comment]
Hi @shazin!

Due to specification, RSocket should be run on top of **reliable** transport, which means that UDP can not work there well! Therefore there RSocket-Aeron (mentioned by @linux-china ) which can help in improving the apps' performance!

I'm closing this issue for now but feel free to let us know if you got anything else related!

Regards,
Oleh

**Comment by phnxfire** [comment]
> Hi @shazin!
> 
> Due to specification, RSocket should be run on top of **reliable** transport, which means that UDP can not work there well! Therefore there RSocket-Aeron (mentioned by @linux-china ) which can help in improving the apps' performance!
> 
> I'm closing this issue for now but feel free to let us know if you got anything else related!
> 
> Regards,
> Oleh

Can you point to a sample where RSocket is being used with Aeron?

**Comment by OlegDokuka** [comment]
@phnxfire we have https://github.com/rsocket/rsocket-transport-aeron, but it is outdated as of now. We are planning to resurrect this implementation in the closest month
