### ISSUE TITLE
GA RoadMap

### ISSUE THREAD

**Issue by pckeyan** [rsocket/rsocket-java#740]
Team,

We are looking to use RSocket in production for which it should be a GA. Can you please let us know the roadmap to GA? And will the SSL issues opened here will be solved before? Please advise.

Thank You
Karthik

**Comment by OlegDokuka** [comment]
Hey!

We are about to release the spec. It will take a couple of weeks to amend the latest changes. 
It means, that we are working on bugfixes and will be doing a release of RSocket-Java near the same time as spec has out.

From the feature-side, what is left right now is to finalize couple of issues related to the spec changes and fix bugs related to fragmentation.

Apart, work is going on other implementations as well, thus keep your eye on it.



> And will the SSL issues opened here will be solved before.

Definitely. Apologies for the huge delay on that question, since I got some other major issues to work on.

Regards,
Oleh

**Comment by pckeyan** [comment]
Thank You @OlegDokuka. I will watch this space and following you and your team on SM.

> work is going on other implementations as well, thus keep your eye on it.

Please highlight if you want me to follow specifically related to rsocket-java. We plan to stick to rscoket-java and not rpc. Thanks again for your help.

Regards
Karthik

**Comment by OlegDokuka** [comment]
1) Fragmentation does not work is it should work
2) We have an issue with TupleByteBuf so that is the root cause of all SSL issues and looks like I have to rollback to CompositeByteBuf again but it is a loss in performance (about 10-15%)
3) Reworking stream call to state-machine as it is done in CPP (https://github.com/rsocket/rsocket-cpp/tree/master/rsocket/statemachine)
4) Finalizing ReconnectingRSocket - https://github.com/rsocket/rsocket-java/pull/685
5) Align implementation with a specified behavior (for now requestChannel can violate spec) (https://github.com/rsocket/rsocket-java/pull/736)
6) Refactoring CompositeMetadata class to extend support for other entries, e.g. AuthMetadataEntry, TaggingMetadataEntry so a user will not have to do that on their own

That is kind of work to do before 1.0.0.RELEASE

**Comment by whyoleg** [comment]
So, when it will be ready, how you will know, that it will be aligned with spec?
I've opened that question long time ago here [TCK](https://github.com/rsocket/rsocket/issues/274).
I received, that you @OlegDokuka are working on something. Is there some progress? May be something already exists, but private?
I've asking, because of my own kotlin(multiplatform in future) implementation [here](https://github.com/whyoleg/rsocket). It's based on rsocket-java, so for now it's just trying to rewrite it, and keep tests working. But it's not so easy to do it like this.
So I will be very grateful, if some TCK exists, or even help to create it.

**Comment by OlegDokuka** [comment]
@whyoleg yes. It is on the road map. So far local test, but I will be working right after the release. TCK is good but it does not bring any value to the final users. Therefore it is the next step. 

If you have anything in mind or any work in progress, I'm open to run a discussion but I don't have enough time to work on that right now .

**Comment by whyoleg** [comment]
@OlegDokuka Thx!
For now, I don't have enough time to work on rsocket (working on other kotlin library, but will start in near future). Also, I'm still waiting for stabilization of rsocket spec and rsocket-java, because now, it's really changing. And also I'm waiting for reworked multiplatform io library (seems will be ready in March-April), it also will lead to big amount refactoring. So I believe, by that time rsocket/rsocket-java will be feature full, so I will be able to work on fully working kotlin MPP rsocket!

About TCK, I really have no experience in something like this, but will look later on old [scala implementation](https://github.com/rsocket/rsocket-tck) for inspiration.

**Comment by pckeyan** [comment]
Thanks So much @OlegDokuka, I will follow above mentioned topics.

**Comment by pckeyan** [comment]
Expecting #716

**Comment by whyoleg** [comment]
Hi @OlegDokuka , are there any estimate for [1.0 milestone](https://github.com/rsocket/rsocket-java/milestone/3)?

**Comment by OlegDokuka** [comment]
It is coming. Planned to be this month

**Comment by rstoyanchev** [comment]
@OlegDokuka, I think this can be closed now that there are [milestones](https://github.com/rsocket/rsocket-java/milestones) representing the roadmap?
