### ISSUE TITLE
InMemoryResumableFrameStore guess FrameSize from ByteBuf

### ISSUE THREAD

**Issue by freelancer1845** [rsocket/rsocket-java#755]
Hey,

I think I stumbled upon a bug. I'm trying to implement the protocol in python (client side) and while implementing the "Resume" feature I ran into a strange problem.

In "**ResumableDuplexConnection:279**" the connection wants to release all unnecessary frames in the frame store.

The FrameStore then releases the frames up to the remoteImpliedPosition (sent from the client).

In "releaseTailFrame" (**InMemoryResumeableFrameStore:145**)" the "frameSize" is guessed by ByteBuf.readableBytes() which returns "writerIndex - readerIndex". While debugging there were instances where this returned 0. 
I changed the call to "ByteBuf.readerIndex()" and it worked but I'm not sure whether one can assume that the buffers are fully read (I guess since they are in the sendframestore they are).
Finally the error appears in the "releaseFrames" function (**InMemoryResumeableFrameStore:58**)" because "removeSize" never reaches zero. The following IllegalSateException is not caught causing the "actionsWip" in ResumableDuplexConnection to not reach zero and the client-side not receiving any further packets.

I think the FrameStore needs to have some knowledge about the size of the frames it stores other than guessing from the netty ByteBuffers.

Cheers

Jascha

**Comment by OlegDokuka** [comment]
Just FYI. Reusability may be changed. For more info please follow -> https://github.com/rsocket/rsocket/issues/300#issuecomment-596664848

**Comment by OlegDokuka** [comment]
@freelancer1845 as of now `position` an `impliedPosition` is based on the frame size for each observed frame https://github.com/rsocket/rsocket/blob/master/Protocol.md#implied-position. Historically happened that instead of counting frames number, we started calculation the position on every frame size instead. In Java, to guess frame size, we use `readableBytes(),` which may work incorrectly if the `ByteBuf` API is misused somewhere. 

The current Java implementation is the best effort. However, other languages can implement the same approach differently (please look at RSocket-JS or RSocket-CPP implementation for more insights).

There are some significant changes scheduled for RSocket spec 2.0. Thus, please pay your attention to this PR https://github.com/rsocket/rsocket/pull/312 before proceeding with the implementation in Python
