### ISSUE TITLE
Deprecate/Drop UriHandler mechanism

### ISSUE THREAD

**Issue by rstoyanchev** [rsocket/rsocket-java#782]
This has no usage within rsocket-java and arguably could be dropped. 

It seems to have been created with the RSocket CLI in mind based on #307 and that's where it seems to be used so one option would be to move it there or drop it completely. It's usage with SSL generally also implies additional transport level setup (see #522).

/cc @yschimke

**Comment by yschimke** [comment]
I wouldn't even deprecate it, just drop it.  I can move into the CLI project.

**Comment by yschimke** [comment]
I added to be a general purpose mechanism to specify unambiguous address schemes.  e.g. a website could have a Rsocket URL to connect to fetch updates.  But all of the connector settings, the setup payloads, and the interaction of operation payloads require prior knowledge.

Within any specific app domain, they can probably specify their own rules. e.g. If I was to start writing a mongo-like competitor, I'd start with RSocket instead of writing my own protocol from wire format up.  In that domain I'd just define that https://, ws://, or tcp:// had some specific interpretation.

Already the CLI has adopted spring extensions, because using the CLI was temporarily useful.  So it's probably not viable to have a truly curl like tool for RSocket anyway.
