### ISSUE TITLE
RSocketResponder: fire-and-forget, metadata-push errors are ignored

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#838]
Some time ago those errors were delivered to `errorConsumer`: (Throwable) -> {}, now they are ignored. Was this change deliberate?

https://github.com/rsocket/rsocket-java/blob/d8da87af65f9f011af8eca0c20e6004a348d3ef0/rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java#L379

**Comment by OlegDokuka** [comment]
This is up to the user on handling `fireAndForget` error and dealing with it on the application level. Since `fnf` is the best effort and responses are deliberately has no effect, supplying this error to the `errorConsumer` makes no sense since the same can be done via the `doOnError` handler or instrumented separately via the interceptor

**Comment by rstoyanchev** [comment]
The `errorConsumer` was too broad of a callback, and while you can get all errors, you never know what exactly they are related because they can be raised from many places and for different requests.

**Comment by OlegDokuka** [comment]
closing this one as answered.

@mostroverkhov feel free to add any comments if you have any other ides related to that one
