### ISSUE TITLE
Expose the stream IDs in RSocket interface and allow developers to use a custom StreamIdSupplier implementation

### ISSUE THREAD

**Issue by JamesChenX** [rsocket/rsocket-java#873]
## Motivation

Our servers want to use unique stream IDs to track the requests across servers so we can diagnose our servers if any RPC failed in our ELK servers, and it should be a common scenario for RPC implementation.

But there are two problems currently:
1. The stream ID isn't exposed in the RSocket interface, so we cannot get the stream IDs to track (More specifically, we want to get the stream ID from the publisher returned by requestResponse method).

2. The default implementation of StreamIdSupplier isn't designed to try to be unique across servers, so RSocket should be able to allow developers (us) to implement their own StreamIdSupplier (e.g. For our cases, we would like to use the snowflake ID generator)

**Although we can add a custom request ID in the payload it's unnecessary and a waste if we can use the stream IDs and the request tracking implementation should be a common scenario.**
## Desired solution

1. Expose the stream IDs in RSocket interface
2. Allow developers to use a custom StreamIdSupplier implementation
## Considered alternatives

No.
## Additional context

No.

**Comment by OlegDokuka** [comment]
Hey @JamesChenX!

First of all, thank you for proposing that!

Secondly, I need to mention that `StreamId` is a specific internal, protocol related value which can not be supplied randomly, it has to follow the spec and exposing `StreamIdSupplier` configuration to the world may lead to some unexpected behavior.

On the other hand, RSocket-CPP (exposes StreamId)[https://github.com/rsocket/rsocket-cpp/blob/master/rsocket/examples/stream-hello-world/StreamHelloWorld_Server.cpp#L36) on the `Responder` side (in the read-only mode). Unfortunately, I do not see a simple way how to do the same for the requester.

Thirdly, don't you wanna use normal Tracing, e.g. Zipkin? Recently we added support for Tracing Zipkin Metadata Extension which expands further integration with that tool. 

That said it can be adopted by your application in order to track RPC calls.

Cheers,
Oleh

**Comment by JamesChenX** [comment]
Hi @OlegDokuka!
Thank you for your fast reply and confirmation.
We will add a custom request ID in the payload for our cases.
And we don't plan to adopt a tracing system currently because our cluster is simple enough and doesn't adopt the heterogeneous microservice architecture, integrating a tracing system is unnecessary for our servers. But thanks for reminding me.
