### ISSUE TITLE
Is there any way to callback a method when remote client is disconnected?

### ISSUE THREAD

**Issue by KaimingWan** [rsocket/rsocket-java#888]
I find doOnConnection in class TcpServer.java. Is there any possible way to init a rsocket server and add callback when remote client is disconnected？

**Comment by OlegDokuka** [comment]
Hi @KaimingWan!

In order to detect remote service disconnection, you may use `onClose` method which is available on the RSocket instance. 

For example, when the new connection is handled, you may `subscribe` to that method so once the connection is lost, `onClose` will send a terminal signal.

```java
RSocketServer
  .create(new SocketAcceptor() {
	 public Mono<RSocket> accept(ConnectionSetupPayload setup, RSocket sendingSocket) {

         sendingSocket
            .onClose()
            .subscribe(null, error -> { /* do on close logic here */ }, () -> { /* do on close logic here */ });
         return ...;
     }
  })
```

As you may see from the example, sendingSocket represent a requester to a just connected client. Using `onClose()` we may listen to when this `RSocket` is closed, which means connection closure (since this is usually 1 to 1 mapping)


Let me know if anything.

Cheers,
Oleh

**Comment by KaimingWan** [comment]
@OlegDokuka Thanks, it works~
