### ISSUE TITLE
Provide Automatic-Module-Name

### ISSUE THREAD

**Issue by aholstenson** [rsocket/rsocket-java#910]
An `Automatic-Module-Name` in the manifest of the published JAR-files would improve Java 9+ compatibility when using modules. Currently you will receive warnings about using an unstable name derived from the module's file name.

## Motivation

Targeting Java 9+ is becoming more common and being able to use RSocket while also using Java modules would be beneficial to those projects.

## Desired solution

Set an `Automatic-Module-Name` for JARs.

## Considered alternatives

A full `module-info.java` for every project could also be added, but is more complicated while also keeping Java 8 support.

**Comment by rstoyanchev** [comment]
For now the low hanging fruit is to declare an "Automatic-Module-Name" in the MANIFEST just like [Reactor](https://github.com/reactor/reactor-core/commit/f8a2dac16903265a00b6e50ee1a69c0cb72b8f57) and [Netty](https://github.com/netty/netty/pull/7245/commits/f35555df2848a41c934f2e366bbc7816deed10fd) have done. 

I propose using a filename convention which is also what Java's [ModuleFinder picks](https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html#of-java.nio.file.Path...-) by default:

- `rsocket.core`
- `rsocket.load.balancer`
- `rsocket.micrometer`
- `rsocket.transport.local`
- `rsocket.transport.netty`

I am aware of the recommendation to use reverse DNS naming based on the root package but this is quite a bit of divergence on this including Reactor which uses the filename convention and Netty which uses reverse DNS naming but based on module names rather than packages. Also modules (`rsocket-core` included) often have more than one top-level package.

**Comment by rstoyanchev** [comment]
Moving to backlog to allow more time for feedback.

**Comment by yschimke** [comment]
Are we happy with this approach now?  Seems like something we should be doing given we are coming up to a second LTS post JDK 9

Example from okhttp as well https://github.com/square/okhttp/blob/f8fd4d08decf697013008b05ad7d2be10a648358/mockwebserver-junit4/build.gradle

**Comment by rstoyanchev** [comment]
This is now superseded by the actual changes in #1007.
