### ISSUE TITLE
RSocket LoadBalancing does not seem to work with Spring Boot.

### ISSUE THREAD

**Issue by vinsguru** [rsocket/rsocket-java#975]
Hi @OlegDokuka 

I was looking at this example and it works just fine.

https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/loadbalancer/RoundRobinRSocketLoadbalancerExample.java

I was trying to implement this with Spring Boot. However it seems to always use the first instance it connects to.

I have a project here. I also have provided the steps as part of README
https://github.com/vinsguru/rsocket-load-balancing

**Server-App:**

- Navigate to server-app cd server-app
- Build the jar mvn clean package
- Run 2 instances of this app as shown below.
```
java -jar -Dspring.rsocket.server.port=6565 target/server-app-0.0.1-SNAPSHOT.jar
java -jar -Dspring.rsocket.server.port=6566 target/server-app-0.0.1-SNAPSHOT.jar
```
**Client-app**

- _application.yaml_ - by default uses the above server instance details - _localhost:6565_ and _localhost:6566_

- Runt the main application.

- Check the server console output. Only one of the instance is processing all the requests!!

Does it require any other config?

**Comment by OlegDokuka** [comment]
@vinsguru thank you for asking!

Basically, the problem is in configurations. Please look at [this stackoverflow answer](https://stackoverflow.com/a/65268468/4891253) for more details

**Comment by OlegDokuka** [comment]
In general, to make it working, please make sure, that your flux provides not a List(SingleDestination) but rather a List(Destination1, Destination2)

**Comment by vinsguru** [comment]
Hi @OlegDokuka ,

I am running 3 instances of the app now.

```
java -jar -Dspring.rsocket.server.port=6565 target/server-app-0.0.1-SNAPSHOT.jar
java -jar -Dspring.rsocket.server.port=6566 target/server-app-0.0.1-SNAPSHOT.jar
java -jar -Dspring.rsocket.server.port=6567 target/server-app-0.0.1-SNAPSHOT.jar
```

The `Flux<List<LoadbalanceTarget>>` will be returning only 2 instances out of 3 from above. Please do note that those 2 nodes will keep changing. 

List(localhost:6565, localhost:6566)
List(localhost:6565, localhost:6566)
List(localhost:6565, localhost:6566)
List(localhost:6565, localhost:6566)
List(localhost:6565, localhost:6566)

**Comment by OlegDokuka** [comment]
@vinsguru the problem is still in configuration

```
private List<LoadbalanceTarget> toLoadBalanceTarget(List<RSocketServer> rSocketServers){
        System.out.println(rSocketServers);
        return rSocketServers.stream()
                .map(server -> LoadbalanceTarget.from(server.getHost() + server.getPort(), TcpClientTransport.create(server.getHost(), server.getPort())))
                .collect(Collectors.toList());
    }
```

As it was mentioned in the stackoverflow answer, the `LoadbalanceTarget` has 1 important parameter which is `key` using `key` the RSocketPool is capable of making difference between given targets and identify which target is new and which has already been there. In your setup, you always use the `localhost` as a key, hence for RSocketPool all the new LoadbalancerTargets seemed to be the same as before, and therefore you observed traffic to only a single target.


Also, please note, that if one of the targets disappears, your connection will be immediately disposed (that is something that we have to improve) which means if the connection is still alive and has ongoing traffic, that traffic will be immediately interrupted and your request will be signaled with `onError`. To fix that, I suggest putting extra retry logic. For example: 

```
    @Override
    public void run(String... args) throws Exception {
        Flux.range(1, 10000)
            .delayElements(Duration.ofMillis(10))
            .flatMap(i -> rSocketRequester.route("square-calculator").data(i).retrieveMono(Integer.class).retry())
            .doOnNext(i -> System.out.println("Response : " + i))
            .blockLast();
    }
```

**Comment by vinsguru** [comment]
OMG!!!!!!!!

Sorry @OlegDokuka. The whole time I was thinking I was using unique key. I just changed to `server.getHost() + server.getPort()` for key. It works just great.

Sorry that I wasted your time.

**Comment by OlegDokuka** [comment]
You are welcome @vinsguru. And no worries!
