### ISSUE TITLE
RSocket channel hangs on 1.1.0

### ISSUE THREAD

**Issue by SerCeMan** [rsocket/rsocket-java#978]
Hi, RSocket Folks!

I noticed that the outgoing channels for clients connected to rsocket-java on 1.1.0 might never be completed in the case of receiving an error. For instance, consider the following "echo" server.
```java
var server = RSocketServer.create( //
    SocketAcceptor.forRequestChannel(in -> {
      return Flux.from(in);
    }))
    .bind(WebsocketServerTransport.create(14243))
    .block();
```

The clients connecting to servers running on `1.0.3` and sending a next message followed by an error message, e.g.
```typescript
subscriber.onNext({data: {msg: 'hello'}})
subscriber.onError(new Error('oh no'))
```

can observe the `requestChannel`'s `Flowable` complete with the error, e.g. 
```typescript
socket.requestChannel(payloads).subscribe({
  onNext(msg) {
    console.log(`onNext ${msg.data}`) // <-- hello arrives first
  }, 
  onError(err) {
    console.log(`onError ${err.message}`) // <-- then the error arrives
  }
});
```

However, the same clients connecting to servers running on `1.1.0` do not observe the error in this case, and the Flowable never completes. At the same time, the servers print an error that signals that the error was dropped. 

```log
[reactor-http-nio-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
ApplicationErrorException (0x201): oh no
	at ...
```

From my debugging, it seems like the issue from the above is happening because `RequestChannelResponderSubscriber` gets terminates on the incoming error, and doesn't deliver anything else afterwards. 
https://github.com/rsocket/rsocket-java/blob/4a64a7c898aec6e42e66a665a2538a4d72985739/rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java#L433-L438

## Expected Behavior
* The clients observing the error coming from the server

## Actual Behavior
* The clients hang

## Steps to Reproduce

Here's the project with the setup reproducing the issue, https://github.com/SerCeMan/rsocket-closing-channel. Based on the version set in `build.gradle`, the jest test is either passing or not. 

## Your Environment

* RSocket version(s) used: `1.0.2` and `1.1.0`
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): `11.0.7`
* OS and version (eg `uname -a`): Mac

**Comment by OlegDokuka** [comment]
closing since that one is invalid and related to incorrect implementation of `requestChannel` at rsocket-js which was working with incorrect implementation for rsocket-java. As you may see there -> https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-core/src/RSocketMachine.js#L448, Flowable publisher does not propagate an error to the actual downstream subscriber. Due to the [spec](https://github.com/rsocket/rsocket/blob/master/Protocol.md#request-channel), 

> Upon receiving an ERROR[APPLICATION_ERROR|REJECTED|CANCELED|INVALID], the stream is terminated on both Requester and Responder.

> Upon sending an ERROR[APPLICATION_ERROR|REJECTED|CANCELED|INVALID], the stream is terminated on both the Requester and Responder. 

that lines clearly state that the error sender MUST be considered terminated and does not expect to receive any more signals from the responder side. 
That said, if a request send an error it has to propagate that error to the downstream do not expect to receive that error from the responder
